# Generated by Django 5.1 on 2025-08-08 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_favoritemovie'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrendingMovie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(choices=[('day', 'Day'), ('week', 'Week')], max_length=10)),
                ('trending_date', models.DateField(auto_now_add=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trending_periods', to='movies.movie')),
            ],
            options={
                'ordering': ['-trending_date'],
                'unique_together': {('movie', 'period', 'trending_date')},
            },
        ),
    ]
