# Generated by Django 5.1 on 2025-08-14 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_alter_movie_poster_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trendingmovie',
            name='period',
            field=models.CharField(choices=[('day', 'Daily'), ('week', 'Weekly')], max_length=10),
        ),
    ]
